
package admin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.freixas.jcalendar.JCalendarCombo;
import koneksi.input;
/**
 *
 * @author User
 */
public class gajipegawai extends javax.swing.JFrame {
  
    public String nip, nama, jekel, tempat, lahir, pendidikan, pangkat, jabatan, masa, gaji;
 
    public String getnip() {
        return nip;
    }
 
    public String getnama() {
        return nama;
    }
 
    public String getjekel() {
        return jekel;
    }
    
    public String gettempat() {
        return tempat;
    }
    public String getlahir() {
        return lahir;
    }
    public String getpendidikan() {
        return pendidikan;
    }
    public String getpangkat() {
        return pangkat;
    }
    
    public String getjabatan() {
        return jabatan;
    }
    public String getmasa() {
        return masa;
    }
    DefaultTableModel tabelModel;


    /**
     * Creates new form datapegawai
     */
    public gajipegawai() {
        initComponents();
        tabelModel = new DefaultTableModel();
        tabeldata.setModel(tabelModel);
        
        tabelModel.addColumn("Nip");
        tabelModel.addColumn("Nama");
        tabelModel.addColumn("Jenis Kelamin");
        tabelModel.addColumn("Tempat");
        tabelModel.addColumn("Tanggal Lahir");
        tabelModel.addColumn("Pendidikan");
        tabelModel.addColumn("Pangkat/Gol");
        tabelModel.addColumn("Jabatan");
        tabelModel.addColumn("Masa Kerja");
        tabelModel.addColumn("Gaji");
        
        tampilTabel();
    
    }
    public void itemTerpilih(){
    NewJFrame fDB = new NewJFrame();
    fDB.fAB = this;
    txtnip.setText(nip);
    txtnama.setText(nama);
    txtjekel.setText(jekel);
    txttempat.setText(tempat);
    txtlahir.setText(lahir);
    txtpendidikan.setText(pendidikan);
    
}
    public void itemTerpilih2(){
    NewJFrame2 fDB = new NewJFrame2();
    fDB.fAC = this;
    txtgol.setText(pangkat);
    txtjabatan.setText(jabatan);
    txtmasa.setText(masa);
    
    
}
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        txtjekel = new javax.swing.JTextField();
        txttempat = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        txtlahir = new javax.swing.JTextField();
        txtpendidikan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtgol = new javax.swing.JTextField();
        txtmasa = new javax.swing.JTextField();
        txtgaji = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-arrow.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 430, 120, 60);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nama Pegawai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 110, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tempat, Tgl Lahir");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 130, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pendidikan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 360, 90, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 280, 110, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Pangkat/Gol");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 200, 90, 17);

        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });
        getContentPane().add(txtnip);
        txtnip.setBounds(150, 190, 210, 40);

        txtjekel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjekelActionPerformed(evt);
            }
        });
        getContentPane().add(txtjekel);
        txtjekel.setBounds(150, 270, 210, 40);

        txttempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempatActionPerformed(evt);
            }
        });
        getContentPane().add(txttempat);
        txttempat.setBounds(150, 310, 130, 40);

        jButton3.setText("....");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 190, 40, 28);
        getContentPane().add(txtnama);
        txtnama.setBounds(150, 230, 210, 40);

        txtlahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlahirActionPerformed(evt);
            }
        });
        getContentPane().add(txtlahir);
        txtlahir.setBounds(280, 310, 120, 40);

        txtpendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpendidikanActionPerformed(evt);
            }
        });
        getContentPane().add(txtpendidikan);
        txtpendidikan.setBounds(150, 350, 190, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Jabatan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 240, 110, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Masa Kerja Gol");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 280, 110, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Gaji Pokok");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(430, 320, 90, 17);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("NIP");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 200, 90, 17);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TMT BARU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 160, 100, 20);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PENGGAJIAN BERKALA");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 120, 260, 30);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DATA PNS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 160, 100, 20);

        txtgol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgolActionPerformed(evt);
            }
        });
        getContentPane().add(txtgol);
        txtgol.setBounds(540, 190, 220, 40);

        txtmasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmasaActionPerformed(evt);
            }
        });
        getContentPane().add(txtmasa);
        txtmasa.setBounds(540, 270, 220, 40);
        getContentPane().add(txtgaji);
        txtgaji.setBounds(540, 310, 220, 40);
        getContentPane().add(txtjabatan);
        txtjabatan.setBounds(540, 230, 220, 40);

        jButton2.setText(".....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 190, 40, 28);

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 430, 120, 60);

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 430, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 826, 560);

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 490, 490, 20);

        setSize(new java.awt.Dimension(810, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menuutama a = new menuutama();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtjekelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjekelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjekelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
    NewJFrame fDB = new NewJFrame();
    fDB.fAB = this;
    fDB.setVisible(true);
    fDB.setResizable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void txttempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempatActionPerformed

    private void txtlahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlahirActionPerformed

    private void txtpendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpendidikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpendidikanActionPerformed

    private void txtmasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmasaActionPerformed

    private void txtgolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgolActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
    NewJFrame2 fDB = new NewJFrame2();
    fDB.fAC = this;
    fDB.setVisible(true);
    fDB.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         try
        {
        Connection konek = input.getKoneksi();
        String query = "UPDATE laporan SET nama = ?, jekel = ?, tempat = ?, tenggal = ?, pendidikan = ?, pangkat = ?, jabatan = ?, masa = ?, gaji = ? WHERE nip = ?";
        PreparedStatement prepare = konek.prepareStatement(query);
       
        
       
        prepare.setString(1, txtnama.getText());
        prepare.setString(2, txtjekel.getText());
        prepare.setString(3, txttempat.getText());
        prepare.setString(4, txtlahir.getText());
        prepare.setString(5, txtpendidikan.getText());
        prepare.setString(6, txtgol.getText());
        prepare.setString(7, txtjabatan.getText());
        prepare.setString(8, txtmasa.getText());
        prepare.setString(9, txtgaji.getText());
        prepare.setString(10, txtnip.getText());
        
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        prepare.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
            System.out.println(ex);
        }
        finally
        {
            tampilTabel();
            refresh();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try
        {
        Connection konek = input.getKoneksi();
        String query = "INSERT INTO laporan VALUES(?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement prepare = konek.prepareStatement(query);
        
        prepare.setString(1, txtnip.getText());
        prepare.setString(2, txtnama.getText());
        prepare.setString(3, txtjekel.getText());
        prepare.setString(4, txttempat.getText());
        prepare.setString(5, txtlahir.getText());
        prepare.setString(6, txtpendidikan.getText());
        prepare.setString(7, txtgol.getText());
        prepare.setString(8, txtjabatan.getText());
        prepare.setString(9, txtmasa.getText());
        prepare.setString(10, txtgaji.getText());
        
        
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        prepare.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data Sudah Ada");
            System.out.println(ex);
        }
        finally
        {

            tampilTabel();
            refresh();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
     public void tampilTabel()
    {
        tabelModel.getDataVector().removeAllElements();
	tabelModel.fireTableDataChanged();
        try
        {
            Connection konek = input.getKoneksi();
            Statement state = konek.createStatement();
            String query = "SELECT * FROM gaji";
            
            ResultSet rs = state.executeQuery(query);
            
            while(rs.next())
            {
                Object obj[] = new Object[10];
                obj[0] = rs.getString(1);
                obj[1] = rs.getString(2);
                obj[2] = rs.getString(3);
                obj[3] = rs.getString(4);
                obj[4] = rs.getString(5);
                obj[5] = rs.getString(6);
                obj[6] = rs.getString(7);
                obj[7] = rs.getString(8);
                obj[8] = rs.getString(9);
                obj[9] = rs.getString(10);
                
                
                tabelModel.addRow(obj);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    public void refresh()
    {
        txtnip.setText("");
        txtnama.setText("");
        txtjekel.setText("");
        txttempat.setText("");
        txtlahir.setText("");
        txtpendidikan.setText("");
        txtgol.setText("");
        txtjabatan.setText("");
        txtmasa.setText("");
        txtgaji.setText("");
        txtnip.requestFocus();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gajipegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gajipegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gajipegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gajipegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gajipegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txtgol;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtjekel;
    private javax.swing.JTextField txtlahir;
    private javax.swing.JTextField txtmasa;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpendidikan;
    private javax.swing.JTextField txttempat;
    // End of variables declaration//GEN-END:variables
}
