
package admin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.freixas.jcalendar.JCalendarCombo;
import koneksi.input;
/**
 *
 * @author User
 */
public class jabatan extends javax.swing.JFrame {
DefaultTableModel tabelModel;
public String cmbx;
public String jabatan;
public static int statusSearching = 0;
public String nip, nama;
 
    public String getnip() {
        return nip;
    }
 
    public String getnama() {
        return nama;
    }
 
  
    /**
     * Creates new form jabatan
     */
    public jabatan() {
        initComponents();
        tabelModel = new DefaultTableModel();
        tabeldata.setModel(tabelModel);
        
        tabelModel.addColumn("Nip");
        tabelModel.addColumn("Nama");
        tabelModel.addColumn("Pangkat/Gol");
        tabelModel.addColumn("Jabatan");
        tabelModel.addColumn("Masa Kerja");
        
        tampilTabel();
    
    }
    public void itemTerpilih(){
    NewJFrame1 fDB = new NewJFrame1();
    fDB.fAB = this;
    txtnip.setText(nip);
    txtnama.setText(nama);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtjabatan = new javax.swing.JTextField();
        txtmasa = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        cmb = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtpangkat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pangkat/Gol");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 260, 100, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jabatan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 300, 80, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Masa Kerja Gol");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 340, 120, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Pegawai");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 220, 110, 20);
        getContentPane().add(txtjabatan);
        txtjabatan.setBounds(140, 290, 180, 40);
        getContentPane().add(txtmasa);
        txtmasa.setBounds(140, 330, 180, 40);
        getContentPane().add(txtnama);
        txtnama.setBounds(140, 210, 180, 40);

        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });
        getContentPane().add(txtnip);
        txtnip.setBounds(140, 170, 180, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NIP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 180, 80, 20);

        jButton1.setText(".....");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 170, 40, 28);

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 170, 420, 240);

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("INPUT JABATAN");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 120, 150, 30);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-arrow.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 420, 100, 50);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-photo.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 420, 100, 50);

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-page-option.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 420, 110, 50);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save (1).png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 420, 100, 50);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bcari.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(540, 430, 50, 40);
        getContentPane().add(txtcari);
        txtcari.setBounds(590, 430, 210, 40);

        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Pilih==", "Ia", "Ib", "Ic", "Id", "IIa", "IIb", "IIc", "IId", "IIIa", "IIIb", "IIIc", "IIId", "IVa", "IVb", "IVc", "IVd", "IVe", " " }));
        cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActionPerformed(evt);
            }
        });
        getContentPane().add(cmb);
        cmb.setBounds(140, 260, 180, 26);

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(110, 420, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 560);
        getContentPane().add(txtpangkat);
        txtpangkat.setBounds(110, 250, 20, 40);

        setSize(new java.awt.Dimension(814, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    NewJFrame1 fDB = new NewJFrame1();
    fDB.fAB = this;
    fDB.setVisible(true);
    fDB.setResizable(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menuutama a = new menuutama();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try
        {
            Connection konek = input.getKoneksi();
            String query = "DELETE FROM tabeljabatan WHERE nip = ?";
            PreparedStatement prepare = konek.prepareStatement(query);
            
            prepare.setString(1, txtnip.getText());
            prepare.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            prepare.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            System.out.println(ex);
        }
        finally
        {
            tampilTabel();
            refresh();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtnip.setText("");
        txtnama.setText("");
        cmb.setSelectedItem("==Pilih==");
        txtjabatan.setText("");
        txtmasa.setText("");
        
        txtnip.requestFocus();
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
        {
        Connection konek = input.getKoneksi();
        String query = "INSERT INTO tabeljabatan VALUES(?,?,?,?,?)";
        PreparedStatement prepare = konek.prepareStatement(query);
        
        prepare.setString(1, txtnip.getText());
        prepare.setString(2, txtnama.getText());
        prepare.setString(3, (String) cmb.getSelectedItem());
        prepare.setString(4, txtjabatan.getText());
        prepare.setString(5, txtmasa.getText());
        
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        prepare.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data Sudah Ada");
            System.out.println(ex);
        }
        finally
        {

            tampilTabel();
            refresh();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try
        {
        Connection konek = input.getKoneksi();
        String query = "UPDATE tabeljabatan SET nama = ?, pangkat = ?, jabatan = ?, masa = ? WHERE nip = ?";
        PreparedStatement prepare = konek.prepareStatement(query);
       
        
       
        prepare.setString(1, txtnama.getText());
        prepare.setString(2,(String) cmb.getSelectedItem());
        prepare.setString(3, txtjabatan.getText());
        prepare.setString(4, txtmasa.getText());
        prepare.setString(5, txtnip.getText());
        
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        prepare.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
            System.out.println(ex);
        }
        finally
        {
            tampilTabel();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    tabelModel.getDataVector().removeAllElements();
	tabelModel.fireTableDataChanged();
        try
        {
            tabelModel.getDataVector().removeAllElements();
            Connection konek = input.getKoneksi();
            String query = "select * from tabeljabatan where nama like '%"+txtcari.getText()+"%'";
            Statement state = konek.createStatement();
            ResultSet rs = state.executeQuery(query);
            
            while(rs.next())
            {
                Object obj[] = new Object[6];
                obj[0] = rs.getString(1);
                obj[1] = rs.getString(2);
                obj[2] = rs.getString(3);
                obj[3] = rs.getString(4);
                obj[4] = rs.getString(5);
                
                
                tabelModel.addRow(obj);
            }
            
        
        } catch(Exception ex)
        {
        }
        finally
        {
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        int a = tabeldata.getSelectedRow();

        if(a == -1)
        {
            return;
        }

        String nip = (String) tabelModel.getValueAt(a, 0);
        txtnip.setText(nip);
        String nama = (String) tabelModel.getValueAt(a, 1);
        txtnama.setText(nama);

        String pangkat = (String) tabelModel.getValueAt(a, 2);
        cmb.setSelectedItem(pangkat);
        String jabatan = (String) tabelModel.getValueAt(a, 3);
        txtjabatan.setText(jabatan);
        String masa = (String) tabelModel.getValueAt(a, 4);
        txtmasa.setText(masa);

    }//GEN-LAST:event_tabeldataMouseClicked

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
    cmbx = (String) cmb.getSelectedItem();
 if (cmbx == "Ia") {
     jabatan = "Juru Muda";
     
 } else if (cmbx == "Ib") {
     jabatan = "Juru Muda Tingkat I";
   
 } else if (cmbx == "Ic") {
     jabatan = "Juru";
     
} else if (cmbx == "Id") {
     jabatan = "Juru Tingkat I";
   
 } else if (cmbx == "IIa") {
     jabatan = "Pengatur Muda";
     
} else if (cmbx == "IIb") {
     jabatan = "Pengatur Muda Tingkat I";
   
 } else if (cmbx == "IIc") {
     jabatan = "Pengatur";
     
} else if (cmbx == "IId") {
     jabatan = "Pengatur Tingkat I";
   
 } else if (cmbx == "IIIa") {
     jabatan = "Penata Muda";
     
} else if (cmbx == "IIIb") {
     jabatan = "Penata Muda Tingkat I";
   
 } else if (cmbx == "IIIc") {
     jabatan = "Penata";
     
} else if (cmbx == "IIId") {
     jabatan = "Penata Tingkat I";
   
 } else if (cmbx == "IVa") {
     jabatan = "Pembiina";
     
     } else if (cmbx == "IVb") {
     jabatan = "Pembina Tingkat I";
   
 } else if (cmbx == "IVc") {
     jabatan = "Pembina Utama Muda";
     
} else if (cmbx == "IVd") {
     jabatan = "Pembina Utama Madya";
   
 } else if (cmbx == "IVe") {
     jabatan = "Pembina Utama";


 }

txtjabatan.setText(jabatan);;
    
    }//GEN-LAST:event_cmbActionPerformed
    public void tampilTabel()
    {
        tabelModel.getDataVector().removeAllElements();
	tabelModel.fireTableDataChanged();
        try
        {
            Connection konek = input.getKoneksi();
            Statement state = konek.createStatement();
            String query = "SELECT * FROM tabeljabatan";
            
            ResultSet rs = state.executeQuery(query);
            
            while(rs.next())
            {
                Object obj[] = new Object[5];
                obj[0] = rs.getString(1);
                obj[1] = rs.getString(2);
                obj[2] = rs.getString(3);
                obj[3] = rs.getString(4);
                obj[4] = rs.getString(5);
                
                
                tabelModel.addRow(obj);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    public void refresh()
    {
        txtnip.setText("");
        txtnama.setText("");
        txtpangkat.setText("");
        txtjabatan.setText("");
        txtmasa.setText("");
        txtnip.requestFocus();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jabatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtmasa;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpangkat;
    // End of variables declaration//GEN-END:variables
}
